# Esercizio 1 — Introduzione a NumPy e manipolazioni di base

**Obiettivi:**
- Generare array casuali con NumPy;
- Calcolare statistiche di base (max, min, std, mean);
- Esercitarsi con maschere logiche, vettori e matrici.


## Setup: importare librerie
Importiamo `pandas` e `numpy` con la sintassi `import <modulo> as <alias>`. In questo notebook useremo soprattutto NumPy:
- `import numpy as np` crea l'alias `np`, così ogni funzione NumPy si richiama come `np.funzione()`;
- `import pandas as pd` è presente per coerenza con gli altri esercizi ma non è strettamente usato in questo file.


In [4]:
import pandas as pd
import numpy as np

## Generare numeri casuali con `np.random.randint`
`np.random.randint(low, high, size)` restituisce un array di interi casuali:
- `low` (incluso) è il valore minimo possibile;
- `high` (escluso) è il valore massimo possibile;
- `size` è il numero di elementi (può essere un int per vettori o una tupla per matrici).
Ogni volta che esegui la cella ottieni numeri diversi perché viene usato il generatore di numeri pseudo-casuali di NumPy.


In [5]:
numeri_random = np.random.randint(low=15, high=30, size = 14)
print(numeri_random)

[28 21 16 22 26 20 16 19 26 23 23 22 16 22]


## Calcolare max/min/std/mean
Applichiamo i metodi vettoriali di NumPy sullo stesso array:
- `array.max()` restituisce il valore massimo;
- `array.min()` restituisce il minimo;
- `array.std()` calcola la deviazione standard (per default popolazione intera);
- `array.mean()` calcola la media aritmetica. 
Questi metodi operano su tutto l'array perché non specifichiamo l'argomento `axis`. L'assegnazione a variabili (`max = ...`) permette di riutilizzare i risultati.


In [6]:
max = numeri_random.max()
min = numeri_random.min()
std = numeri_random.std()
mean = numeri_random.mean()
print(max, min, std, mean)

28 16 3.6589281356759136 21.428571428571427


## Scostamento dalla media
L'espressione `numeri_random - mean` sfrutta il broadcasting di NumPy: ogni elemento dell'array viene sottratto alla costante `mean`. Wrappiamo il risultato in `np.array(...)` (in questo caso ridondante ma didattico) per enfatizzare che otteniamo un nuovo array con gli scostamenti rispetto alla media originale.


In [7]:
days_mean = np.array(numeri_random - mean)
print(days_mean)

[ 6.57142857 -0.42857143 -5.42857143  0.57142857  4.57142857 -1.42857143
 -5.42857143 -2.42857143  4.57142857  1.57142857  1.57142857  0.57142857
 -5.42857143  0.57142857]


## Conteggio elementi sopra la media
`numeri_random > mean` produce un array booleano della stessa lunghezza;
`sum(boolean_array)` in Python somma `True` come 1 e `False` come 0, quindi fornisce il conteggio degli elementi che soddisfano la condizione. In alternativa si può usare `np.sum`, ma qui sfruttiamo la funzione built-in.


In [8]:
days_above_avg = sum(numeri_random > mean)
print(days_above_avg)

8


## Standard Score (z-score)
1. `x.mean()` calcola la media dell'array `x`.
2. `x.std()` calcola la deviazione standard (default popolazione). Puoi passare `ddof=1` per la deviazione campionaria.
3. `z = (x - x_mean) / x_std` applica la formula del punteggio standard per ogni elemento grazie al broadcasting. 
La stampa finale mostra che `z` ha media circa 0 e deviazione circa 1, confermando la standardizzazione.


In [9]:
x = np.array([10, 12, 15, 18, 20, 25])

In [ ]:
x_mean = x.mean()
x_std = x.std()
z = (x-x_mean)/x_std
print(z)
print("Media:", z.mean())
print("Deviazione standard:", z.std())

[-1.32744662 -0.92921264 -0.33186166  0.26548932  0.66372331  1.65930828]
Media: -1.8503717077085943e-16
Deviazione standard: 1.0


## Maschere logiche
- `np.random.randint(0, 101, size=20)` crea 20 interi casuali tra 0 e 100.
- `arr % 2 == 0` restituisce `True` per i numeri pari. Incapsulare il risultato in `np.array(...)` è facoltativo ma sottolinea che il booleano è anch'esso un array.
- `arr[arr % 2 == 0]` applica il boolean indexing: vengono estratti solo gli elementi dove la condizione è `True`.
- Le condizioni combinate `(even_numbers >= 40) & (even_numbers <= 70)` usano gli operatori bitwise `&` e `|` (non `and`/`or`) perché lavoriamo con array NumPy.
- L'assegnazione `even_numbers[condizione] = -1` modifica in-place gli elementi che soddisfano la condizione.


In [17]:
arr = np.random.randint(0, 101, size=20)

In [18]:
even_numbers = np.array(arr % 2 == 0)
print(even_numbers)

[ True  True  True False  True  True  True False False  True False False
  True  True False  True  True  True  True False]


In [19]:
even_numbers = arr[arr % 2 == 0]
print(even_numbers)

[74 48 50 56 80 68 52 32 70  8 94 12 48]


In [20]:
condizione =  (even_numbers >= 40) & (even_numbers <= 70)
between40_70= even_numbers[condizione]
print(between40_70)

[48 50 56 68 52 70 48]


In [ ]:
condizione = (even_numbers >= 90)
even_numbers[condizione] = -1
print(even_numbers)

[74 48 50 56 80 68 52 32 70  8 -1 12 48]


## Vettori e Matrici
Usiamo funzioni NumPy orientate alle matrici:
- `np.random.randint(0, 100, (3, 3))` genera una matrice 3x3 con interi casuali;
- `np.random.randint(0, 100, 3)` genera un vettore di dimensione 3.
Questi oggetti supportano operazioni lineari come prodotto, trasposta e aggregazioni per asse.


##### Matrice
`np.random.randint(0, 100, (3, 3))` usa una tupla per `size`, quindi crea una matrice 3x3. `np.random.randint(0, 100, 3)` crea un vettore di lunghezza 3. Stampiamo entrambi per verificare la struttura.


In [28]:
matrix= np.random.randint(0, 100, (3,3))
vector = np.random.randint(0,100,3)
print(matrix,vector)

[[58 69 11]
 [ 5 74 42]
 [14 57 48]] [75 51 69]


##### Prodotto
`np.dot(matrix, vector)` calcola il prodotto matrice-vettore (somma pesata delle colonne). La funzione esegue automaticamente il controllo sulle dimensioni: una matrice 3x3 può moltiplicare un vettore di lunghezza 3.


In [29]:
prodotto= np.dot(matrix, vector)
print(prodotto)

[8628 7047 7269]


Trasposta della matrice
L'attributo `.T` restituisce la trasposta: le righe diventano colonne e viceversa, utile per cambiare il punto di vista sulle dimensioni.


In [30]:
matrix.T

array([[58,  5, 14],
       [69, 74, 57],
       [11, 42, 48]], dtype=int32)

##### Medie per asse
`matrix.mean(axis=0)` calcola la media colonna per colonna (asse 0 = righe), mentre `matrix.mean(axis=1)` calcola la media riga per riga (asse 1 = colonne). Cambiando `axis` scegli su quale dimensione comprimere i dati.


In [31]:
matrix.mean(axis=0)
matrix.mean(axis=1)

array([46.        , 40.33333333, 39.66666667])

## Riepilogo dettagliato delle funzioni e concetti usati

Di seguito una spiegazione sintetica ma chiara di ogni funzione / metodo / concetto presente nel notebook. Usa questo riepilogo come riferimento rapido.

### Import
- `import numpy as np`: importa la libreria NumPy e assegna l'alias `np` per richiamare le sue funzioni.
- `import pandas as pd`: importa pandas (qui quasi non usata) per coerenza con altri esercizi.

### Generazione di numeri casuali
- `np.random.randint(low, high, size)`: genera interi pseudo‑casuali nell'intervallo `[low, high)`. Se `size` è:
  - un intero: ottieni un vettore 1D;
  - una tupla (es. `(3,3)`): ottieni una matrice con quelle dimensioni.
Pseudo‑casuale significa determinato da un generatore che produce sequenze *apparentemente* casuali.

### Metodi di array (statistiche globali)
Dato un array NumPy (es. `numeri_random`):
- `.max()`: valore massimo.
- `.min()`: valore minimo.
- `.mean()`: media aritmetica (somma / numero elementi).
- `.std()`: deviazione standard (dispersione rispetto alla media). Per default è la *popolazione* (denominatore `N`).
Tutti questi metodi accettano opzionalmente `axis`: se omesso operano sull'intero array.

### Broadcasting
- Espressioni come `numeri_random - mean`: un valore scalare (`mean`) viene esteso automaticamente (broadcast) per eseguire l'operazione elemento‑per‑elemento senza cicli espliciti.

### Maschere booleane
- `numeri_random > mean`: restituisce un array booleano (`True`/`False`) della stessa forma.
- Usato per filtrare / contare.

### Conteggi da booleani
- `sum(maschera)`: in Python `True` vale 1 e `False` vale 0 → somma = conteggio dei `True`. Alternativa: `np.sum(maschera)`.

### Indicizzazione e assegnazione condizionale
Dato un array (es. `even_numbers`):
- `condizione = (even_numbers >= 90)`: crea maschera booleana.
- `even_numbers[condizione] = -1`: sostituisce solo gli elementi che soddisfano la condizione. Questa è *indicizzazione booleana*.

### Matrici e vettori
- `matrix = np.random.randint(0, 100, (3,3))`: matrice 3x3.
- `vector = np.random.randint(0, 100, 3)`: vettore 1D di lunghezza 3.

### Algebra lineare di base
- `np.dot(matrix, vector)`: prodotto matrice‑vettore. Ogni risultato è la somma pesata riga·vettore. (Equivalente a `matrix @ vector`).
- `matrix.T`: trasposta (scambia righe e colonne).

### Aggregazioni per asse
- `matrix.mean(axis=0)`: media di ogni colonna (comprime le righe).
- `matrix.mean(axis=1)`: media di ogni riga (comprime le colonne).
`axis=0` ⇒ scorri verticalmente (colonne risultano), `axis=1` ⇒ scorri orizzontalmente (righe risultano).

### Tipi di dato
- NumPy converte automaticamente in un tipo comune (es. `int32`, `float64`). Operazioni come la sottrazione possono produrre float anche se l'array originale è di interi.

### Buone pratiche
- Evita nomi di variabile che ombreggiano funzioni (`max`, `min`): usali solo in contesti didattici. Preferisci `val_max`, `val_min`.
- Per riprodurre i numeri casuali usa `np.random.seed(valore)`.

Finito il riepilogo: ora dovresti comprendere ogni istruzione incontrata.
